<?php
/*
Intense Snippet Name: The End of Boring
*/
?>

[intense_lead]Aenean quis laoreet quam, vel luctus felis. Proin tincidunt, tellus eu faucibus consectetur, nulla diam cursus sapien, vehicula fringilla arcu justo quis lectus. Nulla tristique dignissim elit ut laoreet. Phasellus sit amet ligula non orci porttitor commodo a sit amet tellus. Sed adipiscing lectus eu mi laoreet condimentum. Aenean pretium pharetra sem sed aliquam. Donec id malesuada turpis.[/intense_lead]

[intense_emphasis  color="#999"]Nullam id dolor euismod, fringilla sapien ut, consequat mi. Aliquam iaculis nisl id pellentesque iaculis. Nullam tempor arcu arcu, id rhoncus sapien convallis vitae. Quisque hendrerit rutrum mauris ut condimentum. Nulla nisl libero, vehicula in pellentesque ac, sollicitudin rutrum magna. Fusce eu euismod orci, vitae aliquam elit. Suspendisse sodales ante sit amet dui dictum porta. Nam rhoncus scelerisque gravida. Duis at felis lectus. Pellentesque fringilla molestie aliquet. Nam nibh enim, adipiscing elementum dignissim ut, lobortis nec nisl. Proin interdum luctus placerat. Maecenas mollis quis est ac vestibulum.[/intense_emphasis]

Donec pulvinar tristique tellus, sed dapibus nisl scelerisque sed. Pellentesque non nunc et felis ornare vulputate. Etiam scelerisque suscipit turpis, varius bibendum turpis gravida vel. Nam sed libero<strong> vitae nisl viverra tristique lobortis id sapien.</strong> Maecenas eget ultricies massa, eu tempus purus. Aliquam blandit scelerisque neque sed hendrerit. Aenean posuere est a dui vestibulum euismod. Vestibulum vitae tortor non eros euismod ultricies et nec neque. Sed pellentesque risus feugiat turpis rhoncus tincidunt. Aenean a tincidunt nibh. Mauris aliquet, sapien sed bibendum sollicitudin, <strong>eros sem elementum eros</strong>, eget dignissim enim odio eu ante. In hac habitasse platea dictumst.

[intense_tabs animation="scale"]
[intense_tab title="In Vitae" border_color="primary"]
[intense_image image="8307" size="postWide" title="Hazy Trees" caption="Proin viverra orci ut arcu porta pharetra." effeckt="2" effecktcolor="#000000" effecktopacity="80" /]
<h2>In vitae eros ante</h2>
Quisque condimentum consectetur tincidunt. Proin nec dui arcu. Praesent eros mauris, fringilla id dolor a, facilisis sagittis dui. Sed convallis condimentum nulla at dignissim. Mauris in sagittis orci, sit amet auctor diam. Maecenas imperdiet dapibus sapien, et porta lectus lobortis in. Proin dictum pulvinar diam, id molestie nibh luctus sit amet.

Maecenas risus arcu, volutpat et semper et, aliquam id mi. Donec bibendum aliquam risus, ac fermentum diam egestas non. Proin ullamcorper suscipit sollicitudin. Sed eget ultrices eros, id tempus orci. Duis sagittis erat quis justo auctor pulvinar. Mauris convallis dictum pellentesque. Quisque eleifend imperdiet est, sed congue mauris imperdiet semper. Maecenas porttitor sapien at viverra cursus. Phasellus pretium dui at justo varius iaculis. Nunc vehicula ipsum nibh. Pellentesque quis erat at libero venenatis cursus eu nec eros. Curabitur et ante non eros iaculis posuere nec non tortor. Sed sit amet massa quam. Donec feugiat suscipit odio vitae elementum.
[/intense_tab]
[intense_tab title="Sed Sit Amet" border_color="success"]
[intense_image image="8312" size="postWide" title="Carmel" caption="Cras dignissim orci lorem, nec tempor quam lobortis in" effeckt="2" effecktcolor="#000000" effecktopacity="80" /]
<h2>Sed sit amet ipsum non quam vehicula imperdiet</h2>
Nunc ornare tempus ipsum, eu pretium nisi imperdiet vel. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent tellus neque, faucibus a auctor sed, interdum at massa. Maecenas dignissim convallis felis, et facilisis felis sagittis a. Aenean eget dignissim lacus. Nam congue imperdiet varius. Integer eget tempus metus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque accumsan facilisis diam quis ultrices. Pellentesque et congue tellus, id ornare nunc. Duis pretium, nisl id adipiscing tempus, neque elit sagittis mi, non mattis risus turpis non ipsum. Duis tempus turpis eget felis vulputate, ut aliquet purus vehicula.

In vitae eros ante. Cras a egestas felis. Nam aliquet luctus lorem, vel tincidunt urna dignissim a. Duis aliquam, odio quis dignissim gravida, est tellus vestibulum nisi, non ultricies nisl sem at tortor. Morbi sit amet dui libero. Nunc scelerisque risus massa, nec viverra arcu rutrum id. Proin pulvinar turpis quam, at pretium nibh consequat non.
[/intense_tab]
[intense_tab title="Aliquam Erat Volutpat" border_color="warning"]
[intense_image image="8298" size="postWide" title="Pier" caption="Phasellus nec rhoncus nibh." effeckt="2" effecktcolor="#000000" effecktopacity="80" /]
<h2>Aliquam erat volutpat</h2>
Sed sit amet ipsum non quam vehicula imperdiet. Nam nec metus sed mauris consectetur convallis. Praesent ut sollicitudin magna, non posuere eros. Cras vulputate velit quis orci luctus fringilla ac et augue. Mauris tellus purus, congue semper condimentum eget, mattis non lectus. Nullam pharetra nisl id purus scelerisque, id lobortis orci dignissim. Sed hendrerit, nisi at venenatis consequat, tellus nisl vestibulum nunc, eu tincidunt tellus nibh vitae turpis. Curabitur pellentesque, sapien faucibus consectetur egestas, elit mauris tincidunt metus, eu consectetur quam lectus non ante. In sed odio id ante ullamcorper feugiat et quis justo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam at feugiat est. Integer pellentesque nisl mi, eu lacinia leo sodales id. Proin a hendrerit tellus.

Aliquam erat volutpat. Proin viverra orci ut arcu porta pharetra. Sed lorem quam, accumsan sit amet mi sit amet, dapibus viverra dui. Sed volutpat libero tortor, id scelerisque lacus lobortis ut. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras a nulla varius, aliquet lacus vitae, suscipit erat. Etiam facilisis, turpis nec pellentesque varius, felis dolor congue erat, non rhoncus urna mauris quis sapien. Mauris varius quis sapien non gravida. Nunc et sollicitudin turpis. Aliquam quis mi cursus, convallis nibh nec, malesuada odio. Nullam gravida, enim at venenatis vestibulum, orci dui rutrum orci, bibendum malesuada tellus nisl non enim. Donec sit amet diam eget dolor elementum fringilla.
[/intense_tab]
[/intense_tabs]

[intense_image image="8353" size="postFull" title="Hey" caption="Nam pellentesque nec risus quis venenatis." effeckt="2" effecktcolor="#000000" effecktopacity="80" shadow="14" /]

[intense_hr type="double" size="large" title="Nunc vel risus in ipsum aliquam cursus" title_background_color="#ffffff" title_position="center" /]

Nunc vel risus in ipsum aliquam cursus. Maecenas id mollis orci. Vestibulum dolor lectus, rhoncus nec orci eget, fringilla blandit tortor. Phasellus ullamcorper porta elementum. Morbi vehicula feugiat justo eu posuere. Suspendisse commodo imperdiet auctor. Curabitur elementum velit at nibh feugiat feugiat. Vivamus ut pharetra felis, sit amet cursus nisi.

Morbi scelerisque aliquam nulla, et porta sem. Sed molestie a odio in aliquet. Nulla eget nibh ultrices, commodo elit non, fringilla tellus. Proin ac aliquet dolor. Nunc aliquam enim at ante varius, sed aliquam mi rhoncus. Pellentesque ultrices, enim quis volutpat scelerisque, nunc orci condimentum sapien, at lacinia nisl lectus ac mauris. Suspendisse adipiscing consectetur dui eget sodales. Fusce mollis mi id velit sagittis, quis ultricies metus euismod. Mauris fringilla risus non nunc congue venenatis. In mauris libero, fringilla in tincidunt sit amet, tempus a libero.

Duis et turpis non augue cursus semper vitae vitae ante. In rhoncus, mi ac varius luctus, magna nibh rutrum erat, in imperdiet libero nisl non est. Pellentesque sagittis sem in metus consequat, ac rutrum odio posuere. Mauris sodales felis sem, vel tristique tortor vehicula nec. Etiam vel nulla pellentesque, ultricies mi ac, mollis erat. Vestibulum vitae ullamcorper libero, id auctor massa. Etiam cursus turpis orci, et rutrum lacus malesuada in. In aliquet est dolor. Integer mollis faucibus magna at mollis. Integer dapibus fermentum nunc sed tincidunt. Donec vitae risus laoreet, egestas erat tempus, blandit dui. Curabitur mattis ipsum vel est facilisis, vitae scelerisque nisl eleifend. Aenean viverra feugiat nisi, at sollicitudin lacus ultrices id. Cras imperdiet nunc ut ipsum feugiat vulputate. Mauris nec erat eget massa congue placerat ut nec neque. Cras arcu augue, pharetra quis ultricies in, accumsan ac sapien.

[intense_image image="8289" size="postWide" title="Berries" caption="Aenean quam nunc, egestas id scelerisque eu, adipiscing quis magna." effeckt="2" effecktcolor="#000000" effecktopacity="80" shadow="14" /]
[intense_hr type="double" size="large" title="Vestibulum dapibus" title_background_color="#ffffff" title_position="center" /]

Vestibulum dapibus porta arcu vel vulputate. Cras eros velit, pharetra tincidunt elit non, ornare semper lacus. Aenean et felis vitae tortor ullamcorper posuere a nec arcu. Aenean adipiscing massa venenatis fringilla ornare. Cras odio risus, laoreet ac augue vitae, pharetra aliquam purus. In ut elit odio. Donec tortor orci, fermentum vitae vestibulum a, gravida id sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc sodales facilisis enim, vitae molestie turpis tristique nec. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla facilisi. Nullam mauris mi, iaculis vitae blandit porta, feugiat ac ante. Quisque interdum, felis id sollicitudin convallis, erat nunc fermentum augue, quis mollis nulla ligula nec magna.

Nunc malesuada molestie libero et malesuada. Suspendisse aliquam, nisl ac placerat tincidunt, nulla felis molestie justo, at ultrices arcu neque ut nisl. Aenean volutpat purus sem, ac feugiat justo mattis ut. Vivamus in semper tortor, vitae tincidunt arcu. Donec in sem sed odio vestibulum vestibulum. Etiam commodo nulla nec nunc pellentesque, eu varius diam molestie. <strong>Praesent dapibus, urna quis convallis fermentum, nisi massa vulputate ipsum, a aliquam libero nisl sed felis.</strong> Vestibulum a elit id erat viverra dapibus sit amet eget tortor. Morbi vel vestibulum leo, et commodo dolor. Fusce convallis augue ac lacus posuere bibendum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla malesuada et massa vitae vestibulum. Cras ac quam tincidunt, imperdiet nibh eget, eleifend neque.

[intense_blockquote rightalign="1"]Sed convallis blandit dolor sed ullamcorper. Vestibulum nec sodales lorem. Vivamus cursus lacus ut blandit varius. Pellentesque semper felis quis ligula egestas gravida. Nullam cursus turpis non ante accumsan porta non quis augue. Donec eu laoreet tellus. Nulla tempor purus et ultricies sodales. Quisque faucibus interdum augue sed ultrices.[/intense_blockquote]

[intense_image image="8296" size="postWide" title="Sky Rose" caption="Fusce dui augue, fermentum vitae lacus ut, condimentum tempor orci." effeckt="2" effecktcolor="#000000" effecktopacity="80" shadow="14" /]

[intense_hr type="double" size="large" title="Sed nunc nibh" title_background_color="#ffffff" title_position="center" /]

Sed nunc nibh, lacinia quis molestie ut, tempor malesuada elit. Curabitur eget ipsum eu ante cursus suscipit at a quam. Vestibulum semper dui augue, a commodo ligula tristique et. Mauris eleifend ligula eu felis lacinia fermentum nec sollicitudin sapien. Integer vitae porta ipsum. Nulla vel urna malesuada nibh semper porta ac id leo. Duis mollis lorem quis dolor pretium suscipit.<strong> Quisque hendrerit dignissim dolor, vitae scelerisque dolor luctus eu.</strong> Vivamus ac mauris in diam lobortis viverra.

Suspendisse molestie, lorem ut sagittis luctus, sem mauris consequat tellus, sit amet feugiat odio dolor non nisi. Curabitur lobortis varius mauris, sit amet elementum justo. Fusce lectus massa, dictum non erat nec, imperdiet cursus odio. Duis in bibendum nibh. Ut nunc metus, volutpat gravida feugiat ut, luctus faucibus leo. Curabitur egestas eleifend erat, suscipit dignissim lectus bibendum quis. Pellentesque tempor adipiscing urna hendrerit viverra. Suspendisse varius ante lectus, non vestibulum arcu varius quis. Praesent nec interdum orci. Nulla vulputate euismod nisi, nec mollis nisi adipiscing sit amet. Integer ac hendrerit neque, facilisis lacinia ipsum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin metus lorem, tempus eu neque euismod, placerat tincidunt tellus.

[intense_emphasis  color="error"]Morbi sollicitudin est facilisis leo commodo imperdiet. Ut porta leo metus, id vulputate tellus tincidunt laoreet. Ut rutrum, mauris a euismod facilisis, est dolor ultrices justo, ut malesuada nibh urna vitae arcu. Curabitur non dapibus libero, sit amet rhoncus magna. Maecenas dui ante, volutpat eu tincidunt ut, facilisis nec odio. Donec volutpat lacinia magna. Sed tellus metus, volutpat ut ultrices id, tincidunt vel eros.[/intense_emphasis]